// create an array and initilize it with some values :

// let array2 = [1, 2, "a"];
// let array3 = [...array1]; // ...=> spread operator

// array3[2] = "b"; // update



// array1[1] = "ydf"; // update

// for (let i = 0; i < array1.length; i++) {
//   console.log(array1[i]);
// }

// Delete

// array1.shift(); // starting value remove
// console.log(array1);

// array1.pop(); // end value removed
// console.log(array1);

// array1.splice(5, 4);
// console.log(array1);

// delete an element from array

// let indexDelete = 2;

// for (let i = indexDelete; i < array1.length; i++) {
//   array1[i] = array1[i + 1];
// }

// array1.length = array1.length - 1;

// for (let i = 0; i < array1.length; i++) {
//   console.log(array1[i]);
// }














