// Maths :

let x = -2.5325252; // 2 ceil
let y = 2.9999999999; // 3
// number => float , int

// console.log(Math.ceil(x)); // 3
// console.log(Math.ceil(y)); // 3

// console.log(Math.floor(x)); // 2
// console.log(Math.floor(y)); // 2

// console.log(Math.round(x));
// console.log(Math.round(y));

// console.log(Math.max(x,y,5));
// console.log(Math.min(y,x,9));

// console.log(Math.abs(x));

// let z = 62354;

// // sqrt (2.5)^1/2 ,
// console.log(Math.pow(2.5, 1/2));
// console.log(Math.sqrt(2.5))

// console.log(Math.exp(3)) // (e)^3

// MM-DD-YY
// let dateObj = new Date(); // object of date class
// console.log(dateObj); // 2024-07-26T05:20:13.645Z
// console.log(typeof dateObj);
// console.log(dateObj.toString());
// console.log(typeof dateObj.toString());
// console.log(dateObj.getDate());
// console.log(dateObj.getDay());

// console.log(dateObj.getFullYear());

// console.log(dateObj.getHours());
// console.log(dateObj.getMilliseconds());
// console.log(dateObj.getTime());
// console.log(dateObj.getSeconds());
// console.log(dateObj.toString());
// console.log(dateObj.toDateString());
// console.log(dateObj.toLocaleString());
// console.log(dateObj.toLocaleDateString());

// let dateObj = new Date(); // object of date class
// let timeStamp = Date.now();

// console.log(dateObj.getTime());
// console.log(Math.floor(timeStamp / 1000));

let stringValue = "u6dk6du6b86v"; // 6 6

// console.log(stringValue.split("").reverse().join(""));

// console.log(stringValue.at(-2));
// console.log(stringValue);

// console.log(stringValue.concat("dtyjdkd"));
console.log(stringValue.substring(1, 5));
console.log(stringValue.includes(" "));

// "Arti" => "itrA"

// let temp = "";

// for (let i = 0; i < stringValue.length; i++) {
//   // temp += stringValue.at(i * -1);

//   temp[i] = stringValue[stringValue.length - 1 - i];
// }
/*
   step 1 : temp[0] = '' +  'i' => 'i'
   step 2 : temp[1] = 'i' + 't' => 'it'
   step 3 : temp[2] = 'it' + 'r' => 'itr'
   step 4 : temp[3] = 'itr' + 'A' => 'itrA'
*/

// console.log(temp);
